import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;

import javax.swing.JOptionPane;



public class Register_restaurant extends javax.swing.JFrame {

	Connection con=MyConnection.getConnection();
    public Register_restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cuisine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cat = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        block = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        pincode = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        accountname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();

        jTextField8.setText("jTextField6");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Join Our Culinary Community: Restaurant Registration");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");

        name.setBackground(new java.awt.Color(0, 204, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone :");

        phone.setBackground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuisine :");

        cuisine.setBackground(new java.awt.Color(0, 204, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description : ");

        desc.setBackground(new java.awt.Color(0, 204, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Category : ");

        cat.setBackground(new java.awt.Color(0, 204, 255));
        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veg", "Non-Veg", "Both" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");

        block.setBackground(new java.awt.Color(0, 204, 255));
        block.setText("block");

        street.setBackground(new java.awt.Color(0, 204, 255));
        street.setText("street");

        area.setBackground(new java.awt.Color(0, 204, 255));
        area.setText("area");

        pincode.setBackground(new java.awt.Color(0, 204, 255));
        pincode.setText("pincode");

        login.setBackground(new java.awt.Color(255, 102, 0));
        login.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Account details:");

        account.setBackground(new java.awt.Color(0, 204, 255));
        account.setText("Account number");

        accountname.setBackground(new java.awt.Color(0, 204, 255));
        accountname.setText("name of account holder");

        password.setBackground(new java.awt.Color(0, 204, 255));
        password.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 47, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(account)
                                    .addComponent(accountname, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(phone)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(113, 113, 113))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cuisine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

                                             

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	
    	try
		{
			Statement st = con.createStatement();
			String query="CREATE TABLE RESTAURANT_INFO (\r\n"
					+ "    Rid VARCHAR(11) CHECK (Rid LIKE 'R%') PRIMARY KEY,\r\n"
					+ "    Rname VARCHAR(50) NOT NULL,\r\n"
					+ "    Rphone NUMBER(10) UNIQUE,\r\n"
					+ "    Ratings NUMBER(1) CHECK (Ratings BETWEEN 0 AND 5),\r\n"
					+ "    Cuisine VARCHAR(50),\r\n"
					+ "    Rdesc VARCHAR(100),\r\n"
					+ "    password VARCHAR(30) CHECK (LENGTH(password) > 8),\r\n"
					+ "    Category VARCHAR(10) \r\n"
					+ ")";

			st.executeUpdate(query);
			
			Statement st1 = con.createStatement();
			String query1="CREATE TABLE RESTAURANT_ADDRESS (\r\n"
					+ "  Rid VARCHAR(13) CHECK(Rid LIKE 'R%'),\r\n"
					+ "  block VARCHAR(20),\r\n"
					+ "  street VARCHAR(20),\r\n"
					+ "  area VARCHAR(30),\r\n"
					+ "  pincode VARCHAR(6),\r\n"
					+ "  PRIMARY KEY (Rid),\r\n"
					+ "  FOREIGN KEY (Rid) REFERENCES RESTAURANT_INFO(Rid)\r\n"
					+ ")";
			st1.executeUpdate(query1);
			
			Statement st3 = con.createStatement();
			String query3="CREATE TABLE RESTAURANT_CRED (\r\n"
					+ "    Rid VARCHAR(13) PRIMARY KEY,\r\n"
					+ "    Raccount NUMBER(11) UNIQUE,\r\n"
					+ "    CHECK (Rid LIKE 'R%'),\r\n"
					+ "    FOREIGN KEY (Rid) References Restaurant_INFO(Rid)\r\n"
					+ ")";

			st3.executeUpdate(query3);
			
			Statement st2 = con.createStatement();
			String query2="CREATE TABLE Restaurant_Acct (\r\n"
					+ "    Raccount NUMBER(11) UNIQUE,\r\n"
					+ "    accountname VARCHAR(30),\r\n"
					+ "    FOREIGN KEY (Raccount) REFERENCES Restaurant_cred(Raccount)\r\n"
					+ ")";

			st2.executeUpdate(query2);
			
			
			
		}
		catch(SQLException e)
		{
			//System.out.println(e);
		}
    	
    	
    	String query="INSERT INTO RESTAURANT_INFO (Rid, Rname, Rphone, Ratings, Cuisine, Rdesc, password, Category) VALUES (?, ?, ?, ?, ?, ?, ?,?)";
   	 	String name_rest= name.getText();
        String phone_rest= phone.getText();
    	 String pass_rest=String.valueOf(password.getPassword());
    	String cuisine_rest= cuisine.getText();
    	String desc_rest= desc.getText();
    	String cat_rest= cat.getSelectedItem().toString();
    	String block_rest= block.getText();
    	String street_rest= street.getText();
    	String area_rest= area.getText();
    	String pincode_rest= pincode.getText();
    	String account_rest=account.getText();
    	String accountname_rest=accountname.getText();
    	
    	if (name_rest.length()==0 || phone_rest.length()==0||block_rest.length()==0||area_rest.length()==0||
    			street_rest.length()==0||area_rest.length()==0 )
    		JOptionPane.showMessageDialog(null,"Please fill out all fields.");
    	else if (pass_rest.length()<8)
     		JOptionPane.showMessageDialog(null,"Password must be atleast 8 characters long");
     	else if (phone_rest.length()!=10)
     		JOptionPane.showMessageDialog(null,"Invalid Phone number");
     	else if (pincode_rest.length()!=6)
     		JOptionPane.showMessageDialog(null,"Invalid Pincode");
     	else
     	{
     		int flag=0;
     		PreparedStatement ps;
    		String rid_trial=IdGenerator.generateRestaurantId();
  
    		//Restaurant Info
    		try
            {
                ps=MyConnection.getConnection().prepareStatement(query);
                
                ps.setString(1,rid_trial);
                ps.setString(2,name_rest);
                ps.setString(3,phone_rest);
                ps.setInt(4,0);
                ps.setString(5,cuisine_rest);
                ps.setString(6, desc_rest);
                ps.setString(7,pass_rest);
                ps.setString(8,cat_rest);
                    
                if (ps.executeUpdate()>0)
                {
                	//JOptionPane.showMessageDialog(null,"Login Successful!\nDelicious Food Delivered to You");
                    System.out.println("CUSTOMER ID : "+rid_trial);
                    
                }
            }
            catch(SQLException e)
            {
            	//JOptionPane.showMessageDialog(null,"An error occurred during login.\nPlease try again shortly.");
            	flag=1;
            	System.out.println("Rest info "+ e);
            }
    		//Restaurant Cred
    		PreparedStatement ps1;
    		
            String query1="INSERT INTO RESTAURANT_CRED (Rid, Raccount) VALUES (?, ?)";
            try
            {
                ps1=MyConnection.getConnection().prepareStatement(query1);
                
                ps1.setString(1,rid_trial);
                ps1.setString(2,account_rest);
                
                   
                if (ps1.executeUpdate()>0)
                {
                    //JOptionPane.showMessageDialog(null,"");
                	//System.out.println("ADDRESS ID : "+aid_trial);
                }
                
                
            }
            catch(SQLException e)
            {
            	//JOptionPane.showMessageDialog(null,"An error occurred during login.\nPlease try again shortly.");
            	flag=1;
            	System.out.println("Rest cred "+ e);
            }
            //Restaurant Acct
            PreparedStatement ps2;
    		
            String query2="INSERT INTO Restaurant_Acct(Raccount, accountname) VALUES (?, ?)";
            		
            try
            {
                ps2=MyConnection.getConnection().prepareStatement(query2);
                
                ps2.setString(1,account_rest);
                ps2.setString(2,accountname_rest);   
                if (ps2.executeUpdate()>0)
                {
                	//JOptionPane.showMessageDialog(null,"Login Successful!\nDelicious Food Delivered to You");
                
                }
                
                
            }
            catch(SQLException e)
            {
            	//JOptionPane.showMessageDialog(null,"An error occurred during login.\nPlease try again shortly.");
            	flag=1;
            	System.out.println("Rest acct "+ e);
            }
            //Restaurant address
            PreparedStatement ps3;
    		
            String query3="INSERT INTO RESTAURANT_ADDRESS (Rid, block, street, area, pincode) VALUES (?, ?, ?, ?, ?)";
            		
            try
            {
                ps3=MyConnection.getConnection().prepareStatement(query3);
                
                ps3.setString(1,rid_trial);
                ps3.setString(2,block_rest);
                ps3.setString(3,street_rest);
                ps3.setString(4,area_rest);
                ps3.setString(5,pincode_rest);
                
                if (ps3.executeUpdate()>0)
                {
                	//JOptionPane.showMessageDialog(null,"Login Successful!\nDelicious Food Delivered to You");
                
                }
                
                
            }
            catch(SQLException e)
            {
            	//JOptionPane.showMessageDialog(null,"An error occurred during login.\nPlease try again shortly.");
            	flag=1;
            	System.out.println("Rest address "+ e);
            }
            if (flag==0)
            	JOptionPane.showMessageDialog(null,"Welcome!\\nReady to Serve More Delicious Food!");
            else
            	JOptionPane.showMessageDialog(null,"An error occurred during login.\nPlease try again shortly.");
            
     	}
    	
    	
    	
    	
    	
    	
    	
    }     //login action ends                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField account;
    private javax.swing.JTextField accountname;
    private javax.swing.JTextField area;
    private javax.swing.JTextField block;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JTextField cuisine;
    private javax.swing.JTextField desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pincode;
    private javax.swing.JTextField street;
    // End of variables declaration   
   
    
    
    
}
